sudo: required
language: minimal
script:
  - sudo ./alpine-make-rootfs
        --branch v3.8
        --packages 'ruby ruby-bigdecimal sqlite'
        --script-chroot
        example-$(date +%Y%m%d).tar.gz -- ./example/install.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: <Encrypted GitHub Personal Token>
#  file: "*.tar.xz"
#  file_glob: true
#  skip_cleanup: true
#  on:
#    tags: true
